/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.smartgov.osmparser.examples.roads;

import java.io.File;
import java.io.IOException;

import javax.xml.bind.JAXBException;

import com.smartgov.osmparser.Osm;
import com.smartgov.osmparser.OsmParser;
import com.smartgov.osmparser.elements.Node;
import com.smartgov.osmparser.elements.Relation;
import com.smartgov.osmparser.filters.elements.TagFilter;
import com.smartgov.osmparser.filters.tags.BaseTagMatcher;

public class Main {

    public static void main(String[] args) throws JAXBException, IOException {
        OsmParser parser = new OsmParser();
        Osm osm = (Osm) parser.parse(new File(Main.class.getResource("../test.osm").getFile()));
        

        parser.setWayFilter(new TagFilter(new BaseTagMatcher("highway", ".*")));
        parser.setWayTagMatcher(new BaseTagMatcher("highway", ".*").or("name", ".*"));

//        parser.addWayTagMatcher(new IncludeTagMatcher("ref", ".*"));
        parser.filterWays();
        System.out.println(osm.getWays());
        
        // osm.addNodeFilter((new RoadNodesFilter(osm.getWays())).or(new ShopFilter()));
        parser.setNodeFilter(new RoadNodesFilter(osm.getWays()));
        parser.filterNodes();
        
        
//        System.out.println(osm.getNodes().size());
//        System.out.println(osm.getNodes());
        
        parser.writeNodes(new File("src/main/resources/com/smartgov/osmparser/examples/roads/nodes.json"));
        parser.writeWays(new File("src/main/resources/com/smartgov/osmparser/examples/roads/ways.json"));

    }
}
